version: '3'
services:


  baby-janus_gateway:
    image: baby-janus_gateway
    ports:
      - "8080:8080"
    build:
      context: ./gateway
    volumes:
      - .:/go/src/github.com/ronna-s/baby-janus/
    networks:
      - network
    environment:
      - VIRTUAL_HOST=gateway.ronna-s

  baby-janus_server:
    image: baby-janus_server
    build:
      context: ./server
    volumes:
      - .:/go/src/github.com/ronna-s/baby-janus/
    networks:
      - network
    depends_on:
      - baby-janus_gateway
    links:
      - baby-janus_gateway
    environment:
      - VIRTUAL_HOST=server.ronna-s
      - CLUSTER_STRATEGY=random

  baby-janus_test_app:
    image: baby-janus_app
    ports:
      - "8081:8080"
    build:
      context: ./app
    volumes:
      - .:/go/src/github.com/ronna-s/baby-janus/
    networks:
      - network
    depends_on:
      - baby-janus_gateway
    links:
      - baby-janus_gateway

networks:
  network: